# Generated by Django 4.2.7 on 2023-11-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=64, verbose_name='Slug'),
        ),
    ]
