# Generated by Django 4.2.7 on 2023-11-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
